version: '2'
services:
    markettradeprocessor-sonar:
        container_name: markettradeprocessor-sonar
        image: sonarqube:5.6-alpine
        ports:
            - 9000:9000
            - 9092:9092
